package com.fooddelivery.customer.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object for customer profile responses.
 * Returned to the client for all customer-related endpoints.
 * Represents the customer profile data stored in customer_db.
 * Never exposes the entity directly to maintain separation
 * between the persistence and presentation layers.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class CustomerResponse {

    /**
     * Unique identifier of the customer profile.
     * Auto-generated by the database.
     */
    private Long customerId;

    /**
     * The unique identifier of the associated user in auth_db.
     * Links the customer profile back to the user account.
     */
    private Long userId;

    /**
     * Full name of the customer.
     */
    private String customerName;

    /**
     * Contact phone number of the customer.
     */
    private String phone;

    /**
     * Delivery address of the customer.
     */
    private String address;
}