package com.fooddelivery.auth.repository;

import com.fooddelivery.auth.entity.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Repository interface for performing CRUD operations
 * on the {@code users} table in auth_db.
 * Extends {@link JpaRepository} to inherit standard
 * database operations such as save, findById, findAll and delete.
 * Custom query methods are auto-generated by Spring Data JPA
 * based on method naming conventions.
 */
@Repository
public interface UserRepository extends JpaRepository<User, Long> {

    /**
     * Retrieves a user by their email address.
     * Used during login to find the user for authentication.
     *
     * @param email the email address to search for
     * @return an {@link Optional} containing the user if found,
     *         or empty if no user exists with the given email
     */
    Optional<User> findByEmail(String email);

    /**
     * Checks whether a user exists with the given email address.
     * Used during registration to prevent duplicate email entries.
     *
     * @param email the email address to check
     * @return {@code true} if a user exists with the email,
     *         {@code false} otherwise
     */
    boolean existsByEmail(String email);
}