# ??? Application Name ???????????????????????????????
spring.application.name=menu-service

# ??? Server Port ????????????????????????????????????
server.port=8082

# ??? MySQL Database Config ??????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/menudb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ??? JPA Config ?????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ??? Eureka Client Config ???????????????????????????
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# ??? Logging ????????????????????????????????????????
logging.pattern.console=%msg%n