package com.fooddelivery.menumodule.repository;

import com.fooddelivery.menumodule.entity.Restaurant;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import java.util.List;
import java.util.Optional;

/**
 * Repository interface for Restaurant entity.
 * Extends JpaRepository providing built-in CRUD operations.
 * Custom query methods auto-generated by JPA method naming convention.
 */
@Repository
public interface RestaurantRepository extends JpaRepository<Restaurant, Long> {

    /**
     * Finds restaurant by owner's user ID.
     * Used after login to load restaurant owner's restaurant.
     *
     * @param userId the user ID of restaurant owner
     * @return Optional containing restaurant if found
     */
    Optional<Restaurant> findByUserId(Long userId);

    /**
     * Finds restaurant by its name.
     * Used during order placement when customer types restaurant name.
     *
     * @param restaurantName the name of restaurant
     * @return Optional containing restaurant if found
     */
    Optional<Restaurant> findByRestaurantName(String restaurantName);

    /**
     * Finds all restaurants in a specific location.
     *
     * @param location the location to search
     * @return list of restaurants in that location
     */
    List<Restaurant> findByLocation(String location);
}