package com.fooddelivery.customer.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing a customer profile in the food delivery system.
 * Mapped to the {@code customers} table in customer_db.
 * Created automatically when a user registers with role {@code CUSTOMER}
 * via a Feign call from auth-service.
 * Linked to the {@code users} table in auth_db through {@code userId}.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "customers")
public class Customer {

    /**
     * Unique identifier for the customer profile.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "customer_id")
    private Long customerId;

    /**
     * The unique identifier of the associated user in auth_db.
     * Links the customer profile to the user account.
     * Must be unique — one customer profile per user.
     */
    @Column(name = "user_id", nullable = false, unique = true)
    private Long userId;

    /**
     * Full name of the customer.
     * Cannot be null.
     */
    @Column(name = "customer_name", nullable = false)
    private String customerName;

    /**
     * Contact phone number of the customer.
     * Optional field.
     */
    @Column(name = "phone")
    private String phone;

    /**
     * Delivery address of the customer.
     * Optional field.
     */
    @Column(name = "address")
    private String address;
}