package com.fooddelivery.api_gateway.util;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.util.Date;

/**
 * Utility class for JWT token validation and data extraction
 * in the API Gateway.
 * Reads and validates tokens generated by the auth-service.
 * Does NOT generate tokens — only validates and reads them.
 * The secret key must match the one used in auth-service
 * to validate tokens correctly.
 */
@Component
public class JwtUtil {

    /**
     * Secret key used for signing and verifying JWT tokens.
     * Must match the {@code jwt.secret} value in auth-service.
     * Injected from {@code application.properties}.
     */
    @Value("${jwt.secret}")
    private String secret;

    /**
     * Creates and returns the HMAC-SHA signing key
     * from the configured secret string.
     * Used internally for token parsing and validation.
     *
     * @return the {@link SecretKey} derived from the secret string
     */
    private SecretKey getSigningKey() {
        return Keys.hmacShaKeyFor(
                secret.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Validates the given JWT token by parsing its claims
     * and checking if it has expired.
     *
     * @param token the JWT token string to validate
     * @return {@code true} if the token is valid and not expired,
     *         {@code false} if the token is invalid, malformed or expired
     */
    public boolean isTokenValid(String token) {
        try {
            getClaims(token);
            return !isTokenExpired(token);
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Extracts the email address (subject) from the JWT token.
     * The email is stored as the subject claim during token generation
     * in auth-service.
     *
     * @param token the JWT token string
     * @return the email address of the authenticated user
     */
    public String extractEmail(String token) {
        return getClaims(token).getSubject();
    }

    /**
     * Extracts the role from the JWT token.
     * The role is stored as a custom claim during token generation
     * in auth-service.
     * One of: CUSTOMER, RESTAURANT_OWNER, AGENT.
     *
     * @param token the JWT token string
     * @return the role of the authenticated user
     */
    public String extractRole(String token) {
        return (String) getClaims(token).get("role");
    }

    /**
     * Checks whether the JWT token has expired
     * by comparing the expiration date with the current date.
     *
     * @param token the JWT token string
     * @return {@code true} if the token has expired,
     *         {@code false} otherwise
     */
    private boolean isTokenExpired(String token) {
        return getClaims(token).getExpiration().before(new Date());
    }

    /**
     * Parses the JWT token and returns its claims payload.
     * Verifies the token signature using the signing key.
     *
     * @param token the JWT token string to parse
     * @return the {@link Claims} payload containing all token data
     * @throws io.jsonwebtoken.JwtException if the token is invalid,
     *         malformed or signature verification fails
     */
    private Claims getClaims(String token) {
        return Jwts.parser()
                .verifyWith(getSigningKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }
}