package com.fooddelivery.auth.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing a user in the food delivery system.
 * Mapped to the {@code users} table in auth_db.
 * A user can be a CUSTOMER, RESTAURANT_OWNER, or AGENT.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier for the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Long userId;

    /**
     * Email address of the user.
     * Must be unique across all users.
     */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /**
     * BCrypt hashed password of the user.
     * Never stored as plain text.
     */
    @Column(name = "password", nullable = false)
    private String password;

    /**
     * Role of the user in the system.
     * Determines access level and profile type.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false)
    private Role role;

    /**
     * Account status of the user.
     * Default is ACTIVE. Can be set to INACTIVE to disable access.
     */
    @Column(name = "status", nullable = false)
    private String status = "ACTIVE";
}