package com.fooddelivery.customer.repository;

import com.fooddelivery.customer.entity.Customer;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Repository interface for performing CRUD operations
 * on the {@code customers} table in customer_db.
 * Extends {@link JpaRepository} to inherit standard
 * database operations such as save, findById, findAll and delete.
 * Custom query methods are auto-generated by Spring Data JPA
 * based on method naming conventions.
 */
@Repository
public interface CustomerRepository extends JpaRepository<Customer, Long> {

    /**
     * Retrieves a customer profile by their associated user ID.
     * Used after login when only the userId from JWT token is available.
     *
     * @param userId the user ID linked to the customer profile
     * @return an {@link Optional} containing the customer if found,
     *         or empty if no customer exists with the given userId
     */
    Optional<Customer> findByUserId(Long userId);

    /**
     * Checks whether a customer profile exists for the given user ID.
     * Used during profile creation to prevent duplicate profiles
     * for the same user.
     *
     * @param userId the user ID to check
     * @return {@code true} if a customer profile exists for the userId,
     *         {@code false} otherwise
     */
    boolean existsByUserId(Long userId);
}